"""add realized pnl to transactions

Revision ID: 69665ac29518
Revises: e31dcad0b446
Create Date: 2026-09-03 16:09:55.406337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69665ac29518'
down_revision: Union[str, Sequence[str], None] = 'e31dcad0b446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'realized_pnl')
    # ### end Alembic commands ###
