"""create market prices table

Revision ID: b01d45d28111
Revises: 69665ac29518
Create Date: 2026-09-03 16:34:45.396707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01d45d28111'
down_revision: Union[str, Sequence[str], None] = '69665ac29518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'price_date', name='uq_market_price_asset_date')
    )
    op.create_index(op.f('ix_market_prices_asset_id'), 'market_prices', ['asset_id'], unique=False)
    op.create_index(op.f('ix_market_prices_price_date'), 'market_prices', ['price_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_prices_price_date'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_asset_id'), table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
